# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-28 08:44
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loglan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
                ('course_description', models.TextField()),
                ('course_slug', models.SlugField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoursePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('course_part_name', models.CharField(max_length=30)),
                ('course_content', models.TextField()),
                ('course_example', models.TextField()),
                ('course_example_answer_key', models.TextField()),
                ('course_point', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_parts', to='loglan.Course')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='CourseTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_takens', to='loglan.Course')),
                ('course_part', models.ManyToManyField(blank=True, related_name='course_takens_part', to='loglan.CoursePart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_takens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='loglan.Course')),
            ],
        ),
        migrations.CreateModel(
            name='QuizPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_part_name', models.CharField(max_length=30)),
                ('quiz_content', models.TextField()),
                ('quiz_point', models.IntegerField()),
                ('course_part_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_parts_course', to='loglan.CoursePart')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_parts', to='loglan.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizPartAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('image_answer', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='QuizTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_takens', to='loglan.Quiz')),
                ('quiz_part_is_completed', models.ManyToManyField(related_name='quiz_takens_is_completed', to='loglan.QuizPart')),
                ('quiz_part_is_false', models.ManyToManyField(related_name='quiz_takens_is_false', to='loglan.QuizPart')),
                ('quiz_part_is_true', models.ManyToManyField(related_name='quiz_takens_is_true', to='loglan.QuizPart')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_taken', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TotalScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='total_score', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(blank=True, max_length=40)),
                ('key_expires', models.DateTimeField(default=datetime.date(2017, 4, 28))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='quizpart',
            name='quiz_answer',
            field=models.ManyToManyField(related_name='quiz_parts_answer', to='loglan.QuizPartAnswer'),
        ),
        migrations.AddField(
            model_name='quizpart',
            name='quiz_answer_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_parts_answer_key', to='loglan.QuizPartAnswer'),
        ),
    ]
