# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-29 04:22
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loglan', '0002_auto_20170428_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizpartanswer',
            name='quiz_part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_part_answers', to='loglan.QuizPart'),
        ),
        migrations.AlterField(
            model_name='quizpartanswer',
            name='image_answer',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='quizpartanswer',
            name='text_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='totalscore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='total_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useractivationkey',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2017, 4, 29)),
        ),
    ]
