# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-05 15:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loglan', '0003_auto_20170404_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_confirmed',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
