# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-11 04:43
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loglan', '0005_useractivationkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
                ('course_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CoursePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('quiz_example', models.TextField()),
                ('answer_key_example', models.TextField()),
                ('course_point', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_parts', to='loglan.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_takens', to='loglan.Course')),
                ('couse_part', models.ManyToManyField(related_name='course_takens', to='loglan.CoursePart')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_taken', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='loglan.Course')),
            ],
        ),
        migrations.CreateModel(
            name='QuizPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_challenge', models.TextField()),
                ('answerkey_challenge', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_parts', to='loglan.Course')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_parts', to='loglan.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_point', models.IntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_takens', to='loglan.Quiz')),
                ('quiz_part_is_completed', models.ManyToManyField(related_name='quiz_takens_is_completed', to='loglan.QuizPart')),
                ('quiz_part_is_true', models.ManyToManyField(related_name='quiz_takens_is_true', to='loglan.QuizPart')),
                ('quiz_part_random', models.ManyToManyField(related_name='quiz_takens_random', to='loglan.QuizPart')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_taken', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TotalScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField()),
                ('user', models.ManyToManyField(related_name='total_scores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='useractivationkey',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2017, 4, 11)),
        ),
    ]
