# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loglan', '0006_auto_20170504_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizpart',
            name='quiz_answer',
        ),
    ]
