# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-11 08:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loglan', '0006_auto_20170411_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizpart',
            old_name='answerkey_challenge',
            new_name='answer_key_challenge',
        ),
        migrations.RemoveField(
            model_name='coursetaken',
            name='couse_part',
        ),
        migrations.AddField(
            model_name='coursetaken',
            name='course_part',
            field=models.ManyToManyField(related_name='course_takens_part', to='loglan.CoursePart'),
        ),
        migrations.AlterField(
            model_name='quizpart',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_parts_course', to='loglan.Course'),
        ),
        migrations.RemoveField(
            model_name='totalscore',
            name='user',
        ),
        migrations.AddField(
            model_name='totalscore',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='total_scores', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
