# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-08 02:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loglan', '0007_remove_quizpart_quiz_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizpart',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='useractivationkey',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2017, 5, 8)),
        ),
    ]
