# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-12 10:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loglan', '0007_auto_20170411_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepart',
            name='course_part_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useractivationkey',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2017, 4, 12)),
        ),
    ]
