# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-12 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loglan', '0008_auto_20170412_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizpart',
            name='quiz_part_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
