# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-08 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loglan', '0008_auto_20170508_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizpart',
            old_name='course_part_name',
            new_name='course_part',
        ),
    ]
