# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-08 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loglan', '0009_auto_20170508_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztaken',
            name='quiz_part_is_completed',
            field=models.ManyToManyField(blank=True, related_name='quiz_takens_is_completed', to='loglan.QuizPart'),
        ),
        migrations.AlterField(
            model_name='quiztaken',
            name='quiz_part_is_false',
            field=models.ManyToManyField(blank=True, related_name='quiz_takens_is_false', to='loglan.QuizPart'),
        ),
        migrations.AlterField(
            model_name='quiztaken',
            name='quiz_part_is_true',
            field=models.ManyToManyField(blank=True, related_name='quiz_takens_is_true', to='loglan.QuizPart'),
        ),
    ]
