# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 03:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loglan', '0009_quizpart_quiz_part_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizpart',
            name='course',
        ),
        migrations.AlterField(
            model_name='useractivationkey',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2017, 4, 13)),
        ),
    ]
