# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loglan', '0010_auto_20170413_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizpart',
            name='course_part_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_parts_course', to='loglan.Course'),
            preserve_default=False,
        ),
    ]
