# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-13 02:44
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loglan', '0010_auto_20170508_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztaken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_taken', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useractivationkey',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2017, 5, 13)),
        ),
    ]
