# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 08:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loglan', '0011_auto_20170513_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursepart',
            options={'ordering': ('course', 'number')},
        ),
        migrations.AlterModelOptions(
            name='quizpart',
            options={'ordering': ('quiz', 'number')},
        ),
        migrations.AlterField(
            model_name='quizpart',
            name='quiz_answer_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_parts_answer_key', to='loglan.QuizPartAnswer'),
        ),
        migrations.AlterField(
            model_name='useractivationkey',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2017, 5, 15)),
        ),
    ]
