# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loglan', '0011_quizpart_course_part_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizpart',
            name='course_part_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_parts_course', to='loglan.CoursePart'),
        ),
    ]
