# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loglan', '0014_auto_20170417_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='slug',
            new_name='course_slug',
        ),
    ]
