# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 07:09
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loglan', '0015_auto_20170417_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepart',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coursetaken',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='totalscore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='total_score', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useractivationkey',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2017, 4, 20)),
        ),
    ]
